configs:
  # Memory Management
  CONFIG_PAHOLE_VERSION: 129
  CONFIG_ARM64_4K_PAGES: y
  CONFIG_ARM64_16K_PAGES: n
  # BCM2711 (Raspberry Pi 4) Hardware Support
  CONFIG_ARCH_BCM2835: y
  CONFIG_BCM2711_THERMAL: y
  CONFIG_PINCTRL_BCM2835: y
  CONFIG_SPI_BCM2835: y
  CONFIG_SPI_BCM2835AUX: y
  CONFIG_I2C_BCM2835: y
  CONFIG_PWM_BCM2835: y
  CONFIG_BCMGENET: y
  CONFIG_DRM_VC4: y
  CONFIG_DRM_VC4_HDMI_CEC: y
  CONFIG_SND_BCM2835: y
  # BCM2712 (Raspberry Pi 5) Hardware Support
  CONFIG_BCM2712_IOMMU: y
  CONFIG_BCM2712_MIP: y
  CONFIG_BCM2835_THERMAL: y
  # RP1 Chip Support (Raspberry Pi 5 I/O controller)
  CONFIG_FIRMWARE_RP1: y
  CONFIG_MFD_RP1: y
  CONFIG_MBOX_RP1: y
  CONFIG_COMMON_CLK_RP1: y
  CONFIG_COMMON_CLK_RP1_SDIO: y
  CONFIG_PINCTRL_BCM2712: y
  CONFIG_PINCTRL_RP1: y
  CONFIG_RP1_PIO: y
  CONFIG_PWM_RP1: y
  CONFIG_PWM_PIO_RP1: y
  # BCM2835 Peripherals
  CONFIG_BCM2835_SMI: m
  CONFIG_BCM2835_SMI_DEV: m
  CONFIG_I2C_BCM2708: y
  CONFIG_BCM2835_VCHIQ: y
  CONFIG_BCM2835_MBOX: y
  CONFIG_BCM2835_WDT: y
  CONFIG_CLK_RASPBERRYPI: y
  CONFIG_RASPBERRYPI_FIRMWARE: y
  # Pin Control & GPIO
  CONFIG_PINCTRL_MCP23S08: y
  CONFIG_GPIO_BCM_VIRT: y
  CONFIG_GPIO_RASPBERRYPI_EXP: y
  CONFIG_PWM_BRCMSTB: y
  CONFIG_PWM_GPIO: y
  CONFIG_SPI_GPIO: y
  CONFIG_SPI_RP2040_GPIO_BRIDGE: y
  # Raspberry Pi Specific
  CONFIG_RASPBERRYPI_GPIOMEM: y
  CONFIG_NVMEM_RASPBERRYPI_OTP: y
  CONFIG_NVMEM_RMEM: y
  CONFIG_MFD_RASPBERRYPI_POE_HAT: y
  CONFIG_RTC_DRV_RPI: y
  # USB Host Controller
  CONFIG_USB_XHCI_HCD: y
  CONFIG_USB_XHCI_PCI: y
  CONFIG_USB_XHCI_PLATFORM: y
  CONFIG_USB_DWC2: y
  # Framebuffer & Display
  CONFIG_FB_BCM2708: y
  CONFIG_FB_RPISENSE: y
  # LED Support
  CONFIG_WS2812_PIO_RP1: y
  # RP1 Sensors
  CONFIG_SENSORS_RP1_ADC: y
  # RP1 Video & Display
  CONFIG_VIDEO_RP1_CFE: m
  CONFIG_DRM_RP1_DSI: m
  CONFIG_DRM_RP1_DPI: m
  CONFIG_DRM_RP1_VEC: m
  # CPU Frequency Governor
  CONFIG_CPU_FREQ_DEFAULT_GOV_ONDEMAND: y
  # Network PHY
  CONFIG_NETWORK_PHY_TIMESTAMPING: y
  # IMA (Integrity Measurement Architecture)
  CONFIG_IMA: y
  CONFIG_IMA_SECURE_AND_OR_TRUSTED_BOOT: y
  CONFIG_IMA_APPRAISE: y
  CONFIG_IMA_APPRAISE_BOOTPARAM: y
  CONFIG_IMA_ARCH_POLICY: y
  CONFIG_IMA_DEFAULT_HASH_SHA512: y
  CONFIG_IMA_DEFAULT_HASH: "sha512"
  CONFIG_IMA_DEFAULT_TEMPLATE: "ima-ng"
  CONFIG_IMA_LSM_RULES: y
  CONFIG_IMA_MEASURE_ASYMMETRIC_KEYS: y
  CONFIG_IMA_MEASURE_PCR_IDX: 10
  CONFIG_IMA_NG_TEMPLATE: y
  CONFIG_IMA_QUEUE_EARLY_BOOT_KEYS: y
  CONFIG_IMA_READ_POLICY: y
  CONFIG_IMA_WRITE_POLICY: y
  CONFIG_HAVE_IMA_KEXEC: y
  # UBSAN
  CONFIG_UBSAN_SIGNED_WRAP: y
  # Disable Features
  CONFIG_BLK_CGROUP_IOLATENCY: n
  CONFIG_DRM_PANTHOR: n
  CONFIG_INFINIBAND_USER_ACCESS: n
  CONFIG_INFINIBAND_USER_MAD: n
  CONFIG_NFT_CONNLIMIT: n
  CONFIG_ZSWAP: n
  # Network Drivers - Built-in for Talos/K8s
  CONFIG_R8169: y
  CONFIG_E1000: y
  CONFIG_E1000E: y
  CONFIG_IGB: y
  CONFIG_IGBVF: y
  CONFIG_IXGBE: y
  CONFIG_IXGBEVF: y
  CONFIG_I40E: y
  CONFIG_I40EVF: y
  CONFIG_IAVF: y
  CONFIG_ICE: y
  CONFIG_IGC: y
  CONFIG_LIBETH: y
  CONFIG_LIBIE: y
  CONFIG_MDIO: y
  CONFIG_VMXNET3: y
  CONFIG_USB_RTL8152: y
  CONFIG_USB_LAN78XX: y
  # Network Drivers - Modules
  CONFIG_8139TOO: m
  CONFIG_AQTION: m
  CONFIG_BNX2: m
  CONFIG_BNX2X: m
  CONFIG_BNXT: m
  CONFIG_CAVIUM_PTP: m
  CONFIG_DP83867_PHY: m
  CONFIG_ENIC: m
  CONFIG_QED: m
  CONFIG_QEDE: m
  CONFIG_QLCNIC: m
  CONFIG_SKY2: m
  CONFIG_TIGON3: m
  # Ethernet MAC Drivers
  CONFIG_DWMAC_DWC_QOS_ETH: y
  CONFIG_DWMAC_GENERIC: y
  CONFIG_DWMAC_IMX8: y
  CONFIG_DWMAC_IPQ806X: y
  CONFIG_DWMAC_MESON: y
  CONFIG_DWMAC_QCOM_ETHQOS: y
  CONFIG_DWMAC_ROCKCHIP: y
  CONFIG_DWMAC_SUN8I: y
  CONFIG_DWMAC_SUNXI: y
  CONFIG_DWMAC_TEGRA: y
  CONFIG_STMMAC_ETH: y
  CONFIG_STMMAC_PCI: y
  CONFIG_STMMAC_PLATFORM: y
  # USB Serial
  CONFIG_USB_SERIAL_CH341: y
  CONFIG_USB_SERIAL_CP210X: y
  CONFIG_USB_SERIAL_FTDI_SIO: y
  CONFIG_USB_SERIAL_PL2303: y
  # Storage Controllers
  CONFIG_BCACHE: y
  CONFIG_BLK_DEV_NVME: y
  CONFIG_SATA_AHCI: y
  CONFIG_MEGARAID_SAS: m
  CONFIG_SCSI_HPSA: m
  CONFIG_SCSI_MPT3SAS: m
  CONFIG_SCSI_SMARTPQI: m
  # PATA - Modules
  CONFIG_PATA_AMD: m
  CONFIG_PATA_MARVELL: m
  CONFIG_PATA_OLDPIIX: m
  CONFIG_PATA_SCH: m
  # MMC/SD Host Controllers
  CONFIG_MMC_SDHCI_ACPI: y
  CONFIG_MMC_SDHCI_BRCMSTB: y
  CONFIG_MMC_SDHCI_CADENCE: y
  CONFIG_MMC_SDHCI_F_SDH30: y
  CONFIG_MMC_SDHCI_IPROC: y
  CONFIG_MMC_SDHCI_MSM: y
  CONFIG_MMC_SDHCI_OF_ARASAN: y
  CONFIG_MMC_SDHCI_OF_DWCMSHC: y
  CONFIG_MMC_SDHCI_OF_ESDHC: y
  CONFIG_MMC_SDHCI_PCI: y
  CONFIG_MMC_SDHCI_PLTFM: y
  CONFIG_MMC_SDHCI_TEGRA: y
  CONFIG_MMC_SDHCI_XENON: y
  # HID Drivers - Modules
  CONFIG_HID_A4TECH: m
  CONFIG_HID_APPLE: m
  CONFIG_HID_BELKIN: m
  CONFIG_HID_CHERRY: m
  CONFIG_HID_CHICONY: m
  CONFIG_HID_CYPRESS: m
  CONFIG_HID_EZKEY: m
  CONFIG_HID_GYRATION: m
  CONFIG_HID_ITE: m
  CONFIG_HID_KENSINGTON: m
  CONFIG_HID_LOGITECH: m
  CONFIG_HID_MICROSOFT: m
  CONFIG_HID_MONTEREY: m
  CONFIG_HID_PANTHERLORD: m
  CONFIG_HID_PETALYNX: m
  CONFIG_HID_SAMSUNG: m
  CONFIG_HID_SUNPLUS: m
  CONFIG_HID_TOPSEED: m
  # I2C
  CONFIG_I2C_ALGOBIT: m
  CONFIG_I2C_I801: m
  CONFIG_I2C_MUX: m
  # Miscellaneous
  CONFIG_HP_ILO: m
  CONFIG_PCS_XPCS: m
  # Virtualization
  CONFIG_VIRTIO_BALLOON: y
  CONFIG_VIRTIO_INPUT: y
  CONFIG_VIRTIO_MMIO: y
  CONFIG_VIRTIO_PCI: y
  CONFIG_VIRTIO_PCI_LIB: y
  CONFIG_VIRTIO_PCI_LIB_LEGACY: y
  # Crypto
  CONFIG_CRYPTO_ZSTD: m
